### ISSUE TITLE
TypeError: SSHError does not take keyword arguments during scp

### ISSUE THREAD

**Issue by ghost** [NetAngels/openssh-wrapper#5]
When sending a large file via ssh_openwrapper.scp, at around 50 megs I get the exception TypeError: SSHError does not take keyword arguments. I'm connecting to remote via PKI. The connection is successful, and scp works until around the 50M point, then the exception is thrown.

**Comment by imankulov** [comment]
Looks like you hit the bug, fixed for about 8 months ago in 6f96311c33 (when the application attempted to raise the SSHError, it died unexpectedly instead.) Also I suppose, that the SSHError itself is raised because your code reached the connection timeout. Please, try following

1) update openssh-wrapper to the latest available version (btw, we've just deployed a significantly refactored release with python 3.3 support to PyPI), type `pip install -U openssh-wrapper`
2) try to increase the value of timeout in constructor from 60 (seconds) to 3600, for example.

Hope this helps. Nonetheless, if the problem still appears after all these actions, please provide the traceback.

**Comment by ghost** [comment]
Changing the timeout on constructor worked. Might want to have an exception telling users sending big  files they need to update timeout.

Thanks!
